name: Fill out dential form when it appers.

on:
  schedule:
    - cron: '29 19 * * 0' # runs at sunday 19:29 UTC which is monday 08:29 in NZDT
  workflow_dispatch:

jobs:
  book-classes:
    runs-on: ubuntu-latest
    steps:
      # This step allows the workflow to access script sin the repo
      - name: Checkout Code
        uses: actions/checkout@v2

      # This step set ups python in the virtual machine
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install packages
      - name: Install Requirements
        run: pip install -r requirements.txt

      # This step sets the timezone
      - name: Set timezone to New Zealand
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Pacific/Auckland"

      # This step will execute the booking script in the virtual machine
      - name: Execute auto_fill script
        working-directory: .

        env:
          # Set up username/password from GitHub secrets so they can be accessed.
          FORM_DATA: ${{ secrets.FORM }}
        run: |
          # Run script to auto fill form
          python ./auto_fill

